// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBduTorcNnOGgAFXvHmHnpBIuhPBClmZO4',
    appId: '1:253847803637:web:e0f64a3b6fa10135e197bc',
    messagingSenderId: '253847803637',
    projectId: 'quickchat-application',
    authDomain: 'quickchat-application.firebaseapp.com',
    storageBucket: 'quickchat-application.appspot.com',
    measurementId: 'G-D3J9ZXNVT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvxHsBAatU6UENUIXPUeOqhSU8-jXcOPw',
    appId: '1:253847803637:android:839979c7593841dde197bc',
    messagingSenderId: '253847803637',
    projectId: 'quickchat-application',
    storageBucket: 'quickchat-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGdUU3e4tLtuhih9H1LIQTq82FbWmsUI',
    appId: '1:253847803637:ios:688e10aecb1a483ee197bc',
    messagingSenderId: '253847803637',
    projectId: 'quickchat-application',
    storageBucket: 'quickchat-application.appspot.com',
    iosClientId: '253847803637-nq9cor76ll6dtdle1thmv5g6lpuho55t.apps.googleusercontent.com',
    iosBundleId: 'com.enescerrahoglu.quickchat',
  );
}
